name: Node.js Package (Github) - Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get package.json version
        uses: ./.github/actions/version
        id: get_version
      - name: echo version in package json
        run: |
          echo ${{steps.get_version.outputs.version}}
      - name: ⚙️ Initialize Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: jkf-servers
          service_account_key: ${{ secrets.GCP_SA_KEY_GITHUB_CI }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Authenticate with GitHub package registry
        run: |
          rm -rf .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_TOKEN }}" >> .npmrc 
          echo "@lctech-tw:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: <NPM> Install and Build
        run: pnpm install && pnpm run build
      - name: <NPM> Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: add changelog in release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload GCS
        run: |
          echo "Upload gcs (lc-public-storage/pan-core)" 
          echo "v${{steps.get_version.outputs.version}}"
          gsutil cp -Z -r ./dist/* gs://lc-public-storage/pan-core/v${{steps.get_version.outputs.version}}
      - name: Slack Notification on Success (O)
        if: success()
        run: |
          echo "run slack on Success (O)"
          curl -LJO https://raw.githubusercontent.com/lctech-tw/util_scripts/main/notify_slack.sh
          bash ./notify_slack.sh -s
      - name: Slack Notification on Failure (X)
        if: failure()
        run: |
          echo "run slack on Fail (X)"
          curl -LJO https://raw.githubusercontent.com/lctech-tw/util_scripts/main/notify_slack.sh 
          bash ./notify_slack.sh -f
